name: telebot_feedback
description: Một thư viện gửi feedback về Telegram kèm thông tin thiết bị và tracking người dùng.
version: 0.0.1
homepage: https://github.com/mdnast/telebot_feedback.git

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0           # Để gọi API Telegram
  device_info_plus: ^10.0.0  # Tự động lấy tên thiết bị (Samsung, iPhone...)
  package_info_plus: ^8.0.0  # Tự động lấy version app (1.0.0)

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

